### PR TITLE
Add action for gh-pages

### PR DESCRIPTION
**Pull request by ericdallo**
Adding a webpage like other LSPs: https://emacs-lsp.github.io/lsp-mode

Screenshot from 2020-05-02 19-47-40

### CODE REVIEW

**Comment by alanz** [comment]
Thanks.

Hopefully one day when installing a server becomes simpler we can move this into the main repo.

**Comment by ericdallo** [comment]
@alanz You need to enable it on the settings of this repo and set the GH pages to the `gh-pages` branch, then the site will be enabled on https://emacs-lsp.github.io/lsp-haskell.

I'll link it [here](https://emacs-lsp.github.io/lsp-mode) too.

I recommend we set the URL in the repo as we did it on [lsp-java](https://github.com/emacs-lsp/lsp-java) and [lsp-dart](https://github.com/emacs-lsp/lsp-dart)
image

**Comment by alanz** [comment]
Ping repo owners. @yyoncho ?

**Comment by ericdallo** [comment]
I thought you were a repo owner, sorry :sweat_smile:

**Pull request merged**
