### PR TITLE
Add haskell-cabal-mode to supported modes

### PR DESCRIPTION
**Pull request by alanz**
Based on https://discourse.haskell.org/t/hsoc-hls-cabal-file-support/7331

### CODE REVIEW

**Review by michaelpj — APPROVED** [review]
Yep, seems right!

**Comment by michaelpj** [comment]
have you tried this, OOI?

**Comment by alanz** [comment]
> have you tried this, OOI?

Nope, I need to tweak my config to load the new one, and was already using an emacs instance.

**Comment by alanz** [comment]
And it looks like the normal windows failure, will merge

**Comment by alanz** [comment]
And it does not work for me, but I think we need `haskell.plugin.cabal.globalOn` and `haskell.plugin.cabal.completionOn`.

https://github.com/haskell/vscode-haskell/blob/4a262a5f0e46b65ffc6eab4f604e0d2c52813612/package.json#L224C10-L235

**Pull request merged**
